### ISSUE TITLE
Additional comma on argument list breaks on PHP < 8.0

### ISSUE THREAD

**Issue by reyostallenberg** [stefandoorn/google-tag-manager-plugin#123]
https://github.com/stefandoorn/google-tag-manager-plugin/blob/7676d864a1246846a476a63e83c79a1f9f481064/src/EventListener/ContextListener.php#L28

There is no PHP version requirement in composer.json therefore this line just breaks projects when installing on PHP lower than 8.0

What can we do about this? In my opinion PHP > 8.0 should be a requirement in composer

**Comment by stefandoorn** [comment]
Which PHP version are you using? I'm not 100% sure, but isn't this also working on PHP 7.4?

**Comment by reyostallenberg** [comment]
In the declaration of a method it's allowed from PHP 8+

See https://php.watch/versions/8.0/trailing-comma-parameter-use-list

**Comment by stefandoorn** [comment]
Ah.. indeed. Will see if I can push a new version without them, and another one with them but with the PHP version requirement :)

**Comment by stefandoorn** [comment]
I think it's fixed now with this release: https://github.com/stefandoorn/google-tag-manager-plugin/releases/tag/v1.2.2

**Comment by reyostallenberg** [comment]
For me it is fixed this way, thanks
