### ISSUE TITLE
OOM when adding channel

### ISSUE THREAD

**Issue by wldjfr** [stefandoorn/google-tag-manager-plugin#6]
Can't add a new channel, getting OOM even with memory_limit at -1

**Comment by stefandoorn** [comment]
Can you show me what command / action you are running?

**Comment by colorzfr** [comment]
Just creating a new channel through the admin/channels/ page

**Comment by stefandoorn** [comment]
Ok. But then I'm not sure it's due to this plugin, or something else. This plugin is not hooking into anything in the admin - mainly frontend shop output.

**Comment by colorzfr** [comment]
i don't look deeper but removing this plugin solve my issue.

**Comment by stefandoorn** [comment]
Ok. I will try to take a look whether I also have this behaviour in my test environment.

**Comment by wldjfr** [comment]
Great, thanks for your reply anyway

**Comment by stefandoorn** [comment]
Found the issue: using channel context inside the admin (it shouldn't). I will look into a fix. Also files a bug in Sylius: https://github.com/Sylius/Sylius/issues/8538. It's kind of unexpected behavior I think.

**Comment by stefandoorn** [comment]
Found the issue. Another improvement will be to not render all things GTM stuff in the admin anyway.
